# Generated by Django 5.0.6 on 2024-07-23 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_datosextra_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosextra',
            name='date_of_birth',
        ),
    ]
